# Generated by Django 3.2.8 on 2022-01-11 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('tour_departure_address', models.CharField(max_length=100)),
                ('tour_description', models.CharField(max_length=150)),
                ('number_of_gigs', models.IntegerField()),
                ('per_diem', models.FloatField()),
                ('travel_days', models.IntegerField()),
                ('travel_day_pay', models.FloatField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('tour_gig_pay', models.FloatField()),
                ('mileage', models.IntegerField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigtaxapi.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('receipt_number', models.BigIntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigtaxapi.category')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigtaxapi.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=100)),
                ('gig_description', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('gig_pay', models.FloatField()),
                ('mileage', models.IntegerField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigtaxapi.musician')),
            ],
        ),
    ]
