# Generated by Django 3.2.8 on 2022-01-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigtaxapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigtaxapi.category'),
        ),
    ]
